const constants = {
  CHANGE_PACMAN_DIRECTION: 'CHANGE_PACMAN_DIRECTION',
  CHANGE_PACMAN_COORDINATES: 'CHANGE_PACMAN_COORDINATES',

  EAT_USUAL_FOOD: 'EAT_USUAL_FOOD',
  EAT_POWER_FOOD: 'EAT_POWER_FOOD',
  SPAWN_FOOD: 'SPAWN_FOOD',

  CANCELL_POWER_MODE: 'CANCELL_POWER_MODE',

  UPDATE_ARENA: 'UPDATE_ARENA',

  GAME_OVER: 'GAME_OVER',
};

const objects = {
  PACMAN: 3,
  WALL: 1,
  FOOD: 2,
  POWER_FOOD: 7,
  FLOOR: 0,
  GHOST: 9,
};

export { constants, objects };
