const constants = {
  CHANGE_PACMAN_DIRECTION: 'CHANGE_PACMAN_DIRECTION',
  CHANGE_PACMAN_COORDINATES: 'CHANGE_PACMAN_COORDINATES',

  EAT_USUAL_FOOD: 'EAT_USUAL_FOOD',
  EAT_POWER_FOOD: 'EAT_POWER_FOOD',
  CANCELL_POWER_MODE: 'CANCELL_POWER_MODE',

  UPDATE_ARENA: 'UPDATE_ARENA',
};

export default constants;
